kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-operator-example-override
  namespace: test-petclinic4
subjects:
  - kind: ServiceAccount
    name: jenkins-operator-example
    namespace: test-petclinic4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-operator-example-override
