= Comparison Demo: AWS and Openshift =

== Pipelines (Tekton) ==

[TODO]
====
1. Trigger pipeline with git repo change (see tutorial?)
1. Nexus repo to make compilation faster?
2. Attempt to create from scratch (new-app? or use raw image stream creation)
  - or instead use OC commands to deploy instead of relying on trigger
2. Setup other aspects of reference pipeline

====

From the instructions link:https://github.com/openshift/pipelines-tutorial/blob/master/install-operator.md[here]

1. Install subscription (in openshift operators)
----
oc apply -f $DEMO_HOME/kube/tekton/tekton-subscription.yaml
----

2. Optionally install tekton dashboard (for visualization) as per link:https://github.com/tektoncd/dashboard[here]

----
oc apply -f $DEMO_HOME/kube/tekton/openshift-tekton-dashboard-release.yaml
oc wait --for=condition=Available deployment/tekton-dashboard -n openshift-pipelines
----

Then you can open the dashboard by hitting this URL.  It will authenticate using OpenShift oauth

----
echo "https://$(oc get route tekton-dashboard -o jsonpath='{.spec.host}' -n openshift-pipelines)/"
----

3. Create a pull secret for registry.redhat.io.  This is needed for the s2i images

----
$DEMO_HOME/scripts/util-create-pull-secret.sh <USER> <PASS> <SECRET_NAME> <PROJECT_NAME>
----

3. Create a tomcat-s2i task

----
oc apply -f kube/tekton/tasks/s2i-tomcat-8.yaml
----

4. Create the tomcat pipeline

----
oc apply -f $DEMO_HOME/kube/tekton/pipelines/petclinic-dev-pipeline-tomcat.yaml
----

When the operator has finished installing, it will install a pipeline service account in all projects that have sufficient permissions to build stuff.  There is also a centralized openshift-pipelines project that holds pipeline supporting pods.  

NOTE: See also tips and tricks from the link:https://github.com/openshift/pipelines-tutorial[pipelines tutorial]

Attempt to start a build after creation of a tomcat app:

git: https://github.com/hatmarch/spring-framework-petclinic.git
revision: spring-5.2.0
image out: image-registry.openshift-image-registry.svc:5000/test-petclinic4/jws-app



== EB Environment ==

_From helloworld-pipeline example link:https://medium.com/@xoor/deploying-a-node-js-app-to-aws-elastic-beanstalk-681fa88bac53[here]_

Run the following script and answer the prompts as per the link above

NOTE: When using eb deploy it appears you must first *commit* (but not push) into the (local) git repo that is referenced in the .git of the folder that you eb initialized in.  The branch it looks to is in .elasticbeanstalk/config.yml.

== Connecting to existing EB Environment with CLI ==

NOTE: See information on link:https://stackoverflow.com/questions/28821632/how-to-configure-eb-cli-with-eb-env-that-is-already-running[this page here].

1. Change to the directory with the git repo that is deployed to eb
2. run `eb init --profile $AWS_PROFILE`
3. Select the application you want to use

== Saving a configuration with the CLI ==

As long as you have <<Connecting to existing EB Environment with CLI,linked an EB application to the CLI>> you can download a configuration using the EB CLI eb config command, as shown in the following example. NAME is the name of your saved configuration.

----
$ eb config get PetClinic3

Configuration saved at: /workspaces/comparison-demo/spring-framework-petclinic/.elasticbeanstalk/saved_configs/PetClinic3.cfg.yml
----

To get a list of configurations, run

----
eb config list
----

== Updating a configuration with the CLI ==

Once you have <<Saving a configuration with the CLI,downloaded a configuration>> you can edit that configuration locally and then update it.

1. First open your configuration file that you downloaded previously (e.g. `.elasticbeanstalk/saved_configs/PetClinic3.cfg.yml`)

** for example, change the description of the configuration

2. Run `eb config put .elasticbeanstalk/saved_configs/PetClinic3.cfg.yml`

3. To apply the configuration, open the console (`eb console` or `eb console -debug` when in a container to get the command to print out the EB console URL)

== Create from a configuration ==

NOTE: For more information on the create command see link:https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-create.html[here]

If you have a valid configuration file, you can use it to create a new environment with the `eb create` command

For example, to use a (local or saved) cfg.yml file named `PetClinic3`

----
$ eb create petclinic-clone --cfg PetClinic3
Creating application version archive "app-200313_080552".
Uploading petclinic-3/app-200313_080552.zip to S3. This may take a while.
Upload Complete.
Environment details for: petclinic-clone
  Application name: petclinic-3
  Region: ap-southeast-2
  Deployed Version: app-200313_080552
  Environment ID: e-qmxmyjbqr7
  Platform: arn:aws:elasticbeanstalk:ap-southeast-2::platform/Tomcat 8.5 with Java 8 running on 64bit Amazon Linux/3.3.3
  Tier: WebServer-Standard-1.0
  CNAME: UNKNOWN
  Updated: 2020-03-13 08:05:58.808000+00:00
Printing Status:
2020-03-13 08:05:57    INFO    createEnvironment is starting.
...

----

== AWS Pipeline ==

_From helloworld-pipeline example link:https://medium.com/@xoor/using-aws-codepipeline-to-automate-deployments-to-elasticbeanstalk-e80ca988ef70[here]_

First create and name the pipeline

* be sure to create a servicerole

Then select your source (GitHub) in this case

== AWS Code Commit ==

First, be sure to setup your access following instructions link:https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up.html[here].

* Add CodeCommitPowerUser policy to your IAM user
* generate a code commit keypair (see link:https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html[Step 3 of this document] for more details on creating a keypair)
* Create a CodeCommit repo
* Copy the SSH key

== AWS Code Deploy Agent ==