= Comparison Demo: AWS and Openshift =

== MySQL Operator ==

See information link:https://blogs.oracle.com/developers/introducing-the-oracle-mysql-operator-for-kubernetes[here] for the operator (which can be found link:https://github.com/oracle/mysql-operator[here]).  Even better instructions are link:https://banzaicloud.com/blog/mysql-on-kubernetes/#how-to-install-oracle-mysql-operator[here] from "banzaicloud"

First install the operator

Then install an agent in the project where you want to install the cluster.  

NOTE: For OpenShift, it appears the mysql instances need elevated permissions so the mysql-agent needs anyuid scc

----
oc apply -f $DEMO_HOME/kube/operators/mysql/mysql-agent.yaml
oc adm policy add-scc-to-user anyuid -z mysql-agent 
----

Create a root password secret to use for the cluster

----
oc create secret generic mysql-root-password --from-literal=password="password"
----

[NOTE]
====
You can let the operator create the password for you.  If you follow this route, you'll need to fish out the password yourself.  Assuming the cluster is named `jws-app-mysql` (running this command in the project in which it is installed):

----
oc get secret jws-app-mysql-root-password -o jsonpath="{.data.password}" | base64 --decode
----
====

Then install an instance of a MySQL Cluster

----
oc apply -f $DEMO_HOME/kube/operators/mysql/mysql-cluster-instance.yaml
----

Next create a service to represent acccess to the current cluster master

----
oc apply -f $DEMO_HOME/kube/operators/mysql/mysql-primary-service.yaml
----

Test access to the database using Adminer

----
oc port-forward svc/jws-app-mysql 3306:3306
docker run -p 8080:8080 -e ADMINER_DEFAULT_SERVER=docker.for.mac.localhost adminer:latest
----

Login as root (using the secret above) and run these commands (from link:https://linuxize.com/post/how-to-create-mysql-user-accounts-and-grant-privileges/[here])

----
CREATE USER 'pc'@'%' IDENTIFIED BY 'petclinic';
CREATE DATABASE petclinic;
GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'%';
----

Or run these on a local command line [red]#FIXME: Untested#
----
oc run mysql-client --image=mysql:5.7 --rm --restart=Never \
    -- mysql -h jws-app-mysql -uroot -ppassword -e "CREATE USER 'pc'@'%' IDENTIFIED BY 'petclinic'; \
      CREATE DATABASE petclinic; \
      GRANT ALL PRIVILEGES ON petclinic.* TO 'pc'@'%';"
----


=== Troubleshooting ===

==== Cluster fails to appear ====

Check the logs of the mysql-operator pod in the mysql-operator project

----
oc logs deployment/mysql-operator -n mysql-operator -f
----

One known issue is that you can't make your clustername too long:

----
E0317 07:08:48.666574       1 controller.go:291] error syncing 'test-petclinic4/mysql-cluster-with-3-replicas': validating Cluster: metadata.name: Invalid value: "mysql-cluster-with-3-replicas": longer than maximum supported length 28 (see: https://bugs.mysql.com/bug.php?id=90601)
----

==== Configuration Error on Pod ====

Check to make sure you've actually created the secret configured for the cluster


== EB Environment ==

_From helloworld-pipeline example link:https://medium.com/@xoor/deploying-a-node-js-app-to-aws-elastic-beanstalk-681fa88bac53[here]_

Run the following script and answer the prompts as per the link above

NOTE: When using eb deploy it appears you must first *commit* (but not push) into the (local) git repo that is referenced in the .git of the folder that you eb initialized in.  The branch it looks to is in .elasticbeanstalk/config.yml.

== Connecting to existing EB Environment with CLI ==

NOTE: See information on link:https://stackoverflow.com/questions/28821632/how-to-configure-eb-cli-with-eb-env-that-is-already-running[this page here].

1. Change to the directory with the git repo that is deployed to eb
2. run `eb init --profile $AWS_PROFILE`
3. Select the application you want to use

== Saving a configuration with the CLI ==

As long as you have <<Connecting to existing EB Environment with CLI,linked an EB application to the CLI>> you can download a configuration using the EB CLI eb config command, as shown in the following example. NAME is the name of your saved configuration.

----
$ eb config get PetClinic3

Configuration saved at: /workspaces/comparison-demo/spring-framework-petclinic/.elasticbeanstalk/saved_configs/PetClinic3.cfg.yml
----

To get a list of configurations, run

----
eb config list
----

== Updating a configuration with the CLI ==

Once you have <<Saving a configuration with the CLI,downloaded a configuration>> you can edit that configuration locally and then update it.

1. First open your configuration file that you downloaded previously (e.g. `.elasticbeanstalk/saved_configs/PetClinic3.cfg.yml`)

** for example, change the description of the configuration

2. Run `eb config put .elasticbeanstalk/saved_configs/PetClinic3.cfg.yml`

3. To apply the configuration, open the console (`eb console` or `eb console -debug` when in a container to get the command to print out the EB console URL)

== Create from a configuration ==

NOTE: For more information on the create command see link:https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-create.html[here]

If you have a valid configuration file, you can use it to create a new environment with the `eb create` command

For example, to use a (local or saved) cfg.yml file named `PetClinic3`

----
$ eb create petclinic-clone --cfg PetClinic3
Creating application version archive "app-200313_080552".
Uploading petclinic-3/app-200313_080552.zip to S3. This may take a while.
Upload Complete.
Environment details for: petclinic-clone
  Application name: petclinic-3
  Region: ap-southeast-2
  Deployed Version: app-200313_080552
  Environment ID: e-qmxmyjbqr7
  Platform: arn:aws:elasticbeanstalk:ap-southeast-2::platform/Tomcat 8.5 with Java 8 running on 64bit Amazon Linux/3.3.3
  Tier: WebServer-Standard-1.0
  CNAME: UNKNOWN
  Updated: 2020-03-13 08:05:58.808000+00:00
Printing Status:
2020-03-13 08:05:57    INFO    createEnvironment is starting.
...

----

== AWS Pipeline ==

_From helloworld-pipeline example link:https://medium.com/@xoor/using-aws-codepipeline-to-automate-deployments-to-elasticbeanstalk-e80ca988ef70[here]_

First create and name the pipeline

* be sure to create a servicerole

Then select your source (GitHub) in this case

== AWS Code Commit ==

First, be sure to setup your access following instructions link:https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up.html[here].

* Add CodeCommitPowerUser policy to your IAM user
* generate a code commit keypair (see link:https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html[Step 3 of this document] for more details on creating a keypair)
* Create a CodeCommit repo
* Copy the SSH key

== AWS Code Deploy Agent ==