apiVersion: v1
kind: Service
metadata:
  labels:
    v1alpha1.mysql.oracle.com/cluster: jws-app-mysql-cluster
  name: jws-app-mysql
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    v1alpha1.mysql.oracle.com/cluster: jws-app-mysql-cluster
    v1alpha1.mysql.oracle.com/role: primary
  type: ClusterIP