apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-image
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/demo-dev/jws-app
  type: image
