apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: petclinic-dev-pipeline-tomcat-run-manual
spec:
  pipelineRef:
    name: petclinic-dev-pipeline-tomcat
  resources:
  - name: app-git
    resourceRef:
      name: petclinic-git
  - name: app-image
    resourceRef:
      name: petclinic-image
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc