= Comparison Walkthrough =

Premise: You have a (petclinic) spring application that you need to  host in the cloud.  Let’s look at how different facets of this are done in AWS and then in OpenShift

== Local creation ==

Show our demo running locally 

In a local shell, go to the springboot directory and run the following commands

----
source scripts/shell-setup.sh
cd $DEMO_HOME/spring-framework-petclinic
code . 
----

VSCode will open.  Indicate that you want to run in a container.

Next compile the application locally (NOTE: The HSQLDB will use local in memory database)

----
./mvnw install -PHSQLDB -DskipTests
----

[NOTE]
.If you really want to run from SQL
====
Next, we need to make sure we have some sort of MySQL running for this.  The MySQL profile expects to connect on docker.for.mac.localhost:3306 

1. Run from a docker container 
----

----

2. Run connected to the sqlserver in the dev directory

----
oc port-forward -n petclinic-dev svc/jws-app-sql 3306:3306
----
====

Add a tomcat server

Debug the generated .war file in the tomcat server to run locally

Open remote extension, make sure port is forwarded and click link to try out getting to the site

POTENTIALLY: Loop around to show CRC running on local laptop?

== Development Environment Creation ==

How to get our application deployed to Dev

=== AWS ===
Show how ElasticBeanstalk provisions multiple VM with RDS

Show LoadBalancers and reference Route53


=== OpenShift ===

1. Create a new project

----
oc create project petclinic-dev
----

2. Show the creation of a new MySQL cluster using the cluster YAML

----
$DEMO_HOME/scripts/create-sql-cluster.sh 
----

3. Create from template 

* mention that this could be done from templates if we weren't worried about ongoing maintainance of the database

NOTE: Run this from the spring-boot instance

----
oc new-app --template=jws31-tomcat8-basic-s2i --param=SOURCE_REPOSITORY_URL='https://github.com/hatmarch/spring-framework-petclinic.git' --param=SOURCE_REPOSITORY_REF='test-trigger' --param=CONTEXT_DIR='' 
----



Show MySQL operator and then CR for provisioning of database
Show Template for creating a tomcat app
S2I

How Services and replicasets are an analog to Load Balancers and ASG

NOTE: AZ vs. Nodes

== Continuous Integration ==

Show that checking into a git repo can trigger integration chain and deployment to dev

=== AWS ===
Show CodeDeploy with EB

=== Openshift ===
Show Tekton (OpenShift Pipeline) or Jenkins with Openshift

== Production Environments ==

Show how we create additional environments and update pipeline to be able to deploy into these

=== AWS ===
 Show creation of staging and production environment in EB

=== OpenShift ===

Show creation of staging and production projects in OS

Deploy the latest

Deploy a rollback

[NOTE]
====
But first need to make sure image stream is tagged appropriately in the CICD project where is the sha for an image in the local test-petclinic4 image registry for app jws-app

----
oc tag test-petclinic4/jws-app@sha256:3330273342340f89508bdd3ad0fb6ffcfef74dc8991921f9246402809e48a499 test-petclinic4/jws-app:1.0
----
====

== Monitoring Application ==

=== AWS ===

CloudWatch

=== OpenShift ===

See link:https://medium.com/logistimo-engineering-blog/tomcat-jvm-metrics-monitoring-using-prometheus-in-kubernetes-c313075af727[here] for getting information into Prometheus 

== Debugging Application ==
